FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential peg

COPY . /minias
WORKDIR /minias
RUN make
RUN make install DESTDIR=/install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
